### ISSUE TITLE
Missing serial library

### ISSUE THREAD

**Issue by romainreignier** [fco-edno/cmdMessenger-cpp#1]
Hi,
You have done an interesting job, congratulation!
I was about to write my own implementation of cmdMessenger in C++ before finding yours.
I would like to try it, but the files to handle the serial port are missing.
Which library are you using?
Maybe you could give some information about it in the README.
Thanks.
Romain

**Comment by romainreignier** [comment]
Ok, it seems that this is this one  : https://github.com/wjwwood/serial

**Comment by xico42** [comment]
Sorry, i wrote this library a long time ago and never maintained it. I have an online doxygen documentation here: http://fco-edno.github.io/robot/CmdMessenger/index.html

It may help you. There is an example and information about what the library provides.

**Comment by romainreignier** [comment]
Ok, thank you for your answer.
And did you use it like this or move to another solution ?

**Comment by xico42** [comment]
At the time, i used the library as it is. It worked pretty well. It was a mobile robot that i built using ROS and the Microsoft Kinect sensor. I used arduino to read distance measurements from ultrassonic sensors and to drive two DC Motors.

Here a short video:
https://www.youtube.com/watch?v=_IjyENt_nGg

To my needs, it worked perfectly. If you could fork it and improve the library, it would be great.

**Comment by romainreignier** [comment]
Ok, I see. I have used rosserial_arduino for the same kind of setup.
Nice robot by the way! It has a nice behavior.
Yes, I would use it and maybe improve it if needed but I am not sure yet if I will use a serial communication. As I have several Arduino to talk with, I may try to use a RS-485 bus to be able to daisy-chain them, a bit like the Dynamixel servomotors.
Anyway, thanks for the infos.
